import { cookies } from 'next/headers';
import { db,initialize,passwordHash,constantEqual,randomToken,digest,validOrigin } from '../../auth';
export const dynamic='force-dynamic';
export async function POST(req:Request){try{if(!validOrigin(req))return Response.json({error:'Origem inválida'},{status:403});await initialize();const b=await req.json() as any;if(b.action==='logout'){const jar=await cookies();const t=jar.get('rem_session')?.value;if(t)await db().prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(t)).run();return Response.json({ok:true},{headers:{'Set-Cookie':'rem_session=; HttpOnly; Secure; SameSite=None; Partitioned; Path=/; Max-Age=0'}});}
const username=typeof b.username==='string'?b.username.trim().toLowerCase():'';const password=typeof b.password==='string'?b.password:'';if(!/^[a-z0-9._-]{3,60}$/.test(username)||password.length>200)return Response.json({error:'Usuário ou senha incorretos.'},{status:401});
const key=await digest(`${req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'local'}:${username}`);const now=Date.now();await db().prepare('INSERT INTO auth_attempts(key,count,reset) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN auth_attempts.reset<? THEN 1 ELSE auth_attempts.count+1 END,reset=CASE WHEN auth_attempts.reset<? THEN excluded.reset ELSE auth_attempts.reset END').bind(key,now+900000,now,now).run();const attempt=await db().prepare('SELECT count FROM auth_attempts WHERE key=?').bind(key).first<any>();if(attempt.count>10)return Response.json({error:'Muitas tentativas. Tente novamente em 15 minutos.'},{status:429});
const user=await db().prepare('SELECT * FROM app_users WHERE username=? AND active=1').bind(username).first<any>();const hash=await passwordHash(password,user?.salt||'unknown-user-constant-salt');if(!user||!constantEqual(hash,user.password_hash))return Response.json({error:'Usuário ou senha incorretos.'},{status:401});
const token=randomToken();await db().batch([db().prepare('INSERT INTO sessions(token_hash,username,expires) VALUES (?,?,?)').bind(await digest(token),username,now+28800000),db().prepare('DELETE FROM auth_attempts WHERE key=?').bind(key),db().prepare('DELETE FROM sessions WHERE expires<?').bind(now)]);return Response.json({ok:true},{headers:{'Set-Cookie':`rem_session=${token}; HttpOnly; Secure; SameSite=None; Partitioned; Path=/; Max-Age=28800`}});
}catch(e){console.error(e);return Response.json({error:'Não foi possível entrar. Tente novamente.'},{status:503});}}
