'use client';
import {useEffect,useState,useRef} from 'react';
import {Download,Save,Send,CheckCircle2,RotateCcw,ChevronDown,ChevronRight,Search,CalendarRange} from 'lucide-react';
import {BUDGET_STAGES,MONTHS} from './budget-catalog';
import {STATUS_LABELS,sumMonths,type BudgetPlan,type BudgetAmounts} from './budget-types';
const COMPANIES=['ALPAN','REM Construtora','REM Vendas'];
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);
const categories=[...new Set(BUDGET_STAGES.map(s=>s.category))];
export default function BudgetWorkspace({member,areas,onDirtyChange}:{member:{role:string;sector:string};areas:string[];onDirtyChange:(dirty:boolean)=>void}){
 const admin=member.role==='admin'; const requests=useRef(0);
 const [year,setYear]=useState(2027),[company,setCompany]=useState(COMPANIES[1]),[sector,setSector]=useState(admin?(areas[0]||''):member.sector),[plans,setPlans]=useState<BudgetPlan[]>([]),[history,setHistory]=useState<any[]>([]),[amounts,setAmounts]=useState<BudgetAmounts>({}),[note,setNote]=useState(''),[version,setVersion]=useState(0),[status,setStatus]=useState<BudgetPlan['status']>('draft'),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState('Todas'),[open,setOpen]=useState<string[]>([categories[0]]),[onlyFilled,setOnlyFilled]=useState(false);
 const selected=plans.find(p=>p.year===year&&p.company===company&&p.sector===sector);
 const totals=sumMonths(amounts),annual=totals.reduce((a,b)=>a+b,0),allTotals=Array.from({length:12},(_,m)=>plans.reduce((v,p)=>v+sumMonths(p.amounts)[m],0)),allAnnual=allTotals.reduce((a,b)=>a+b,0);
 const locked=!admin&&['submitted','approved'].includes(status);
 async function fetchPlans(){const request=++requests.current;setLoading(true);try{const r=await fetch(`/api/budget?year=${year}`);const d=await r.json();if(!r.ok)throw Error(d.error);if(request!==requests.current)return;setPlans(d.plans);setHistory(d.history);setError('');}catch(e:any){if(request===requests.current)setError(e.message);}finally{if(request===requests.current)setLoading(false);}}
 useEffect(()=>{setPlans([]);setHistory([]);fetchPlans();return()=>{requests.current++;};},[year]);
 useEffect(()=>{onDirtyChange(dirty);return()=>onDirtyChange(false);},[dirty,onDirtyChange]);
 useEffect(()=>{setAmounts(selected?.amounts||{});setNote(selected?.note||'');setVersion(selected?.version||0);setStatus(selected?.status||'draft');setDirty(false);},[selected,company,sector,year]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function switchScope(action:()=>void){if(dirty&&!confirm('Há alterações não salvas. Deseja descartá-las?'))return;action();setError('');setToast('');}
 async function save(action:string){setBusy(true);setError('');try{const r=await fetch('/api/budget',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({year,company,sector,amounts,note,version,action})});const d=await r.json();if(!r.ok)throw Error(d.error);setPlans(old=>[...old.filter(p=>!(p.company===company&&p.sector===sector)),d.plan]);setDirty(false);setToast(action==='submit'?'Orçamento enviado para revisão.':action==='approve'?'Orçamento aprovado.':action==='return'?'Ajustes solicitados ao gestor.':'Orçamento salvo.');await fetchPlans();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 function change(id:string,m:number,value:string){const cents=Math.round(Number(value)*100);setAmounts(old=>({...old,[id]:(old[id]||Array(12).fill(0)).map((v,i)=>i===m?cents:v)}));setDirty(true);setToast('');}
 function repeat(id:string){setAmounts(old=>({...old,[id]:Array(12).fill(old[id]?.[0]||0)}));setDirty(true);}
 async function download(all=false){setBusy(true);setError('');try{if(dirty)throw Error('Salve as alterações antes de exportar.');const params=new URLSearchParams({year:String(year)});if(!all){params.set('company',company);params.set('sector',sector);}const r=await fetch(`/api/budget/export?${params}`);if(!r.ok){const d=await r.json();throw Error(d.error);}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`REM_Orcamento_${year}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const filtered=BUDGET_STAGES.filter(s=>(category==='Todas'||s.category===category)&&(!query||`${s.code} ${s.name} ${s.group}`.toLowerCase().includes(query.toLowerCase()))&&(!onlyFilled||(amounts[s.id]||[]).some(v=>v>0)));
 const scopeHistory=history.filter(h=>h.company===company&&h.sector===sector);
 return <section className="budget-workspace">
 <div className="budget-title"><div><span className="eyebrow">PLANEJAMENTO FINANCEIRO</span><h1>Orçamento por setor</h1><p>Previsão mensal de despesas administrativas por etapa.</p></div><div className="page-buttons"><button className="secondary" disabled={busy||loading} onClick={()=>download(false)}><Download size={16}/> Excel do setor</button>{admin&&<button className="secondary" disabled={busy||loading} onClick={()=>download(true)}>Excel consolidado</button>}</div></div>
 <div className="budget-filters"><label>Ano<select value={year} disabled={busy} onChange={e=>switchScope(()=>setYear(Number(e.target.value)))}>{Array.from({length:11},(_,i)=>2025+i).map(y=><option key={y}>{y}</option>)}</select></label><label>Empresa<select value={company} disabled={busy} onChange={e=>switchScope(()=>setCompany(e.target.value))}>{COMPANIES.map(c=><option key={c}>{c}</option>)}</select></label><label>Setor<select value={sector} disabled={!admin||busy} onChange={e=>switchScope(()=>setSector(e.target.value))}><option value="" disabled>Selecione uma área</option>{(admin?areas:[member.sector]).map(s=><option key={s}>{s}</option>)}</select></label><div className={'budget-status '+status}>{STATUS_LABELS[status]}{dirty&&<small> • alterações não salvas</small>}</div></div>
 {error&&<div role="alert" className="error">{error} <button className="secondary" disabled={busy} onClick={()=>switchScope(()=>{setDirty(false);fetchPlans();})}>Recarregar</button></div>}{toast&&<div role="status" className="budget-notice">{toast}</div>}
 {loading?<div className="panel budget-loading">Carregando orçamento de {year}…</div>:<>
 <div className="budget-kpis"><article><span>Previsão anual do setor</span><strong>{money(annual)}</strong><small>{company} · {sector||'Selecione um setor'}</small></article><article><span>Média mensal</span><strong>{money(annual/12)}</strong><small>{Object.values(amounts).filter(v=>v.some(n=>n>0)).length} etapas preenchidas</small></article><article><span>{admin?'Consolidado de todas as áreas':'Total do seu setor nas empresas'}</span><strong>{money(allAnnual)}</strong><small>{plans.length} orçamentos · {plans.filter(p=>p.status==='approved').length} aprovados</small></article></div>
 <section className="panel budget-chart"><div className="panel-heading"><div><h2>Distribuição mensal</h2><p>Previsão de desembolso do setor selecionado</p></div><CalendarRange size={20}/></div><div className="budget-month-chart">{totals.map((v,m)=><div key={m}><span title={money(v)}>{money(v)}</span><div className="budget-chart-track"><i style={{height:`${v?Math.max(3,v/Math.max(...totals,1)*100):0}%`}}/></div><small>{MONTHS[m]}</small></div>)}</div></section>
 {admin&&<details className="panel budget-overview" open><summary>Visão da Controladoria <span>{plans.length} orçamentos</span></summary><div className="table-wrap"><table><thead><tr><th>Empresa</th><th>Setor</th><th>Previsão anual</th><th>Situação</th><th>Última alteração</th><th/></tr></thead><tbody>{plans.map(p=><tr key={p.company+p.sector}><td>{p.company}</td><td>{p.sector}</td><td className="cost">{money(sumMonths(p.amounts).reduce((a,b)=>a+b,0))}</td><td><span className={'budget-status '+p.status}>{STATUS_LABELS[p.status]}</span></td><td>{p.updated_by}<small className="budget-updated">{new Date(p.updated_at).toLocaleString('pt-BR')}</small></td><td><button className="secondary" disabled={busy} onClick={()=>switchScope(()=>{setCompany(p.company);setSector(p.sector);})}>Abrir</button></td></tr>)}</tbody></table>{!plans.length&&<p className="empty">Os orçamentos salvos pelos setores aparecerão aqui.</p>}</div></details>}
 <section className="panel budget-editor"><div className="panel-heading"><div><h2>Despesas previstas</h2><p>Valores mensais em reais. Abra uma categoria para preencher as etapas.</p></div><span className="pill">{year}</span></div><div className="budget-editor-tools"><div className="search"><Search size={16}/><input aria-label="Buscar etapa" placeholder="Buscar código ou descrição" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filtrar categoria" value={category} onChange={e=>{setCategory(e.target.value);if(e.target.value!=='Todas')setOpen(old=>[...new Set([...old,e.target.value])]);}}><option>Todas</option>{categories.map(c=><option key={c}>{c}</option>)}</select><label className="check"><input type="checkbox" checked={onlyFilled} onChange={e=>setOnlyFilled(e.target.checked)}/> Só preenchidas</label></div>
 {locked&&<div className="budget-lock">{status==='approved'?'Orçamento aprovado.':'Orçamento enviado à Controladoria.'} A edição será liberada quando o Adriano solicitar ajustes.</div>}
 {categories.filter(c=>filtered.some(s=>s.category===c)).map(c=>{const stages=filtered.filter(s=>s.category===c),expanded=open.includes(c)||!!query||onlyFilled;const ct=BUDGET_STAGES.filter(s=>s.category===c).reduce((v,s)=>v+(amounts[s.id]||[]).reduce((a,b)=>a+b,0),0);return <div className="budget-category" key={c}><button className="budget-category-toggle" aria-expanded={expanded} onClick={()=>setOpen(old=>old.includes(c)?old.filter(x=>x!==c):[...old,c])}>{expanded?<ChevronDown size={16}/>:<ChevronRight size={16}/>}<span>{c}</span><strong>{money(ct)}</strong></button>{expanded&&<div className="table-wrap budget-grid"><table><thead><tr><th>Etapa / descrição</th>{MONTHS.map(m=><th key={m}>{m}</th>)}<th>Total anual</th><th/></tr></thead><tbody>{stages.map((s,i)=>{const v=amounts[s.id]||Array(12).fill(0);return <tr key={s.id}><td><span className="budget-code">{s.code} <small>{s.group}</small></span><strong>{s.name}</strong></td>{v.map((val,m)=><td key={m}><input type="number" inputMode="decimal" aria-label={`${s.name} — ${MONTHS[m]}`} min="0" max="1000000" step="0.01" placeholder="0,00" value={val?val/100:''} disabled={locked||busy||!sector} onChange={e=>change(s.id,m,e.target.value)}/></td>)}<td className="budget-row-total">{money(v.reduce((a,b)=>a+b,0))}</td><td><button type="button" className="budget-repeat" title="Repetir o valor de janeiro nos 12 meses" aria-label={`Repetir janeiro: ${s.name}`} disabled={locked||busy||!sector} onClick={()=>repeat(s.id)}><RotateCcw size={14}/></button></td></tr>;})}</tbody></table></div>}</div>;})}
 {!filtered.length&&<div className="empty">Nenhuma etapa encontrada.</div>}
 <div className="budget-grand-total"><span>TOTAL DO SETOR <small>{company} · {sector}</small></span><strong>{money(annual)}</strong></div>
 <div className="budget-review"><label>{admin?'Observação da Controladoria / motivo dos ajustes':'Justificativa e observações'}<textarea rows={3} maxLength={2000} value={note} disabled={locked||busy} placeholder="Explique os principais gastos e premissas do orçamento." onChange={e=>{setNote(e.target.value);setDirty(true);}}/></label><div className="budget-save-actions"><span>{selected?`Última alteração: ${selected.updated_by} · versão ${version}`:'Orçamento ainda não salvo'}{dirty?' • pendente de salvar':''}</span><div>{!locked&&<button className="secondary" disabled={busy||!sector} onClick={()=>save('save')}><Save size={16}/>{busy?'Processando…':'Salvar rascunho'}</button>}{!locked&&status!=='submitted'&&<button className="primary" disabled={busy||!sector} onClick={()=>save('submit')}><Send size={16}/> Enviar para revisão</button>}{admin&&status==='submitted'&&<button className="primary" disabled={busy||dirty} onClick={()=>save('approve')}><CheckCircle2 size={16}/> Aprovar orçamento</button>}{admin&&['submitted','approved'].includes(status)&&<button className="secondary" disabled={busy||!note.trim()} onClick={()=>save('return')}>Solicitar ajustes</button>}</div></div></div>
 </section>
 <details className="panel budget-history"><summary>Histórico de alterações <span>{scopeHistory.length} recentes</span></summary>{scopeHistory.length?<ul>{scopeHistory.map(h=><li key={h.id}><span>{new Date(h.created_at).toLocaleString('pt-BR')}</span><strong>{h.actor}</strong><span>{{save:'Salvou rascunho',submit:'Enviou para revisão',approve:'Aprovou',return:'Solicitou ajustes'}[h.action as string]||h.action} · v{h.version}</span></li>)}</ul>:<p>Nenhuma alteração registrada neste orçamento.</p>}</details>
 <p className="cost-note">Este módulo registra as despesas informadas pelos setores. Os custos do cadastro de funcionários são consultados e exportados separadamente; não são somados automaticamente para evitar duplicidade.</p>
 </>}
 </section>;
}
