'use client';
import {useState} from 'react';
import {BUDGET_STAGES} from './budget-catalog';
import {groupKey} from './budget-groups';
import {Dialog,normalize} from './ui-utils';
import {Search,Save} from 'lucide-react';
export default function BudgetAssignments({area,busy,onSave,onClose}:{area:{name:string;budget_groups?:string[]};busy:boolean;onSave:(b:any)=>Promise<boolean>;onClose:()=>void}){
 const [selected,setSelected]=useState<string[]>(()=>BUDGET_STAGES.filter(s=>(area.budget_groups||[]).includes(groupKey(s))||(area.budget_groups||[]).includes(`stage:${s.id}`)).map(s=>s.id)),[query,setQuery]=useState(''),[error,setError]=useState('');
 const categories=[...new Set(BUDGET_STAGES.map(s=>s.category))],filtered=BUDGET_STAGES.filter(s=>normalize(`${s.code} ${s.name} ${s.group} ${s.category}`).includes(normalize(query)));
 function toggle(ids:string[],checked:boolean){setSelected(old=>checked?[...new Set([...old,...ids])]:old.filter(id=>!ids.includes(id)));}
 return <Dialog title={`Atribuir orçamento · ${area.name}`} wide onClose={()=>{if(!busy)onClose();}}><p>Selecione o que este setor deve preencher. A Controladoria continua podendo consultar e editar todos os itens.</p><div className="assignment-toolbar"><div className="search"><Search size={16}/><input placeholder="Buscar despesa, grupo ou código" aria-label="Buscar atribuições" value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{selected.length} / {BUDGET_STAGES.length} itens</span><button className="secondary" disabled={busy} onClick={()=>setSelected(BUDGET_STAGES.map(s=>s.id))}>Selecionar todos</button><button className="secondary" disabled={busy} onClick={()=>setSelected([])}>Limpar seleção</button></div><div className="assignment-catalog">{categories.filter(c=>filtered.some(s=>s.category===c)).map(c=>{const all=BUDGET_STAGES.filter(s=>s.category===c),visible=filtered.filter(s=>s.category===c);return <details key={c} open={!!query}><summary><span>{c}</span><small>{all.filter(s=>selected.includes(s.id)).length} / {all.length}</small></summary><label className="check assignment-category"><input type="checkbox" disabled={busy} checked={all.every(s=>selected.includes(s.id))} onChange={e=>toggle(all.map(s=>s.id),e.target.checked)}/> Atribuir toda a categoria</label>{[...new Set(visible.map(s=>s.group))].map(g=><div key={g} className="assignment-group"><strong>{g}</strong>{visible.filter(s=>s.group===g).map(s=><label className="check" key={s.id}><input type="checkbox" disabled={busy} checked={selected.includes(s.id)} onChange={e=>toggle([s.id],e.target.checked)}/><span>{s.name}<small>{s.code}</small></span></label>)}</div>)}</details>;})}</div><p className="employee-section-help">Alterar a atribuição não exclui valores antigos. Itens retirados ficam restritos à Controladoria. Nenhum item selecionado bloqueia o preenchimento do setor.</p>{error&&<div role="alert" className="error">{error}</div>}<div className="modal-actions"><button className="secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary" disabled={busy} onClick={async()=>{if(await onSave({action:'saveAreaBudgets',name:area.name,groups:selected.map(id=>`stage:${id}`)}))onClose();else setError('Não foi possível salvar a atribuição. Tente novamente.');}}><Save size={16}/>{busy?'Salvando…':'Salvar atribuição'}</button></div></Dialog>;
}
