'use client';
import {sumMonths,STATUS_LABELS,type BudgetPlan} from './budget-types';
import {BUDGET_STAGES,MONTHS} from './budget-catalog';
import {formatMoney as money} from './ui-utils';
export default function BudgetConsolidation({plans,year,onOpen}:{plans:BudgetPlan[];year:number;onOpen:(p:BudgetPlan)=>void}){
 const months=Array.from({length:12},(_,m)=>plans.reduce((sum,p)=>sum+sumMonths(p.amounts)[m],0)),total=months.reduce((a,b)=>a+b,0);
 const entries=BUDGET_STAGES.map(stage=>({...stage,values:Array.from({length:12},(_,m)=>plans.reduce((sum,p)=>sum+(p.amounts[stage.id]?.[m]||0),0))})).filter(s=>s.values.some(v=>v!==0));
 return <><section className="panel consolidation-table"><div className="panel-heading"><div><h2>Orçamento consolidado · {year}</h2><p>Valores somados das empresas e áreas selecionadas nos filtros.</p></div><div><small>Total anual</small><h2>{money(total)}</h2></div></div><div className="table-wrap"><table><thead><tr><th>Despesa</th>{MONTHS.map(m=><th key={m}>{m}</th>)}<th>Total anual</th></tr></thead><tbody>{[...new Set(entries.map(s=>s.category))].map(category=><tr key={category}><td><strong>{category}</strong></td>{MONTHS.map((_,m)=><td key={m}>{money(entries.filter(s=>s.category===category).reduce((sum,s)=>sum+s.values[m],0))}</td>)}<td className="cost">{money(entries.filter(s=>s.category===category).reduce((sum,s)=>sum+s.values.reduce((a,b)=>a+b,0),0))}</td></tr>)}</tbody><tfoot><tr><td><strong>TOTAL DO ORÇAMENTO</strong></td>{months.map((v,m)=><td key={m}><strong>{money(v)}</strong></td>)}<td className="cost"><strong>{money(total)}</strong></td></tr></tfoot></table></div>{!entries.length&&<p className="empty">Nenhum valor previsto para os filtros selecionados.</p>}</section><details className="panel consolidation-table"><summary>Despesas detalhadas</summary><div className="table-wrap"><table><thead><tr><th>Despesa</th>{MONTHS.map(m=><th key={m}>{m}</th>)}<th>Total anual</th></tr></thead><tbody>{entries.map(s=><tr key={s.id}><td>{s.name.replace(/ \(ADM\)/g,'')}</td>{s.values.map((v,m)=><td key={m}>{money(v)}</td>)}<td className="cost">{money(s.values.reduce((a,b)=>a+b,0))}</td></tr>)}</tbody></table></div></details><details className="panel consolidation-table clean-budget-list"><summary>Revisar ou editar orçamento de uma área</summary><div className="table-wrap"><table><thead><tr><th>Empresa</th><th>Setor</th><th>Situação</th><th>Total anual</th><th/></tr></thead><tbody>{plans.map(p=><tr key={p.company+p.sector}><td>{p.company}</td><td>{p.sector}</td><td>{STATUS_LABELS[p.status]}</td><td>{money(sumMonths(p.amounts).reduce((a,b)=>a+b,0))}</td><td><button className="secondary" onClick={()=>onOpen(p)}>Editar orçamento</button></td></tr>)}</tbody></table></div></details></>;
}
