'use client';
import {costs} from './costs';
import type {Employee} from './employee-form';
import {Dialog,MonthlyChart,formatMoney as money,FULL_MONTHS} from './ui-utils';
import {Users,TrendingUp,CalendarRange,Pencil} from 'lucide-react';
export function PersonnelInsights({employees}:{employees:Employee[]}){
 const totals=Array.from({length:12},(_,m)=>employees.reduce((v,e)=>v+costs(e).monthlyValues[m],0)),impact=employees.reduce((v,e)=>v+costs(e).adjustmentImpact,0),adjusted=employees.filter(e=>!!e.adjustmentRate),annual=totals.reduce((a,b)=>a+b,0),peak=totals.indexOf(Math.max(...totals));
 return <section className="panel personnel-forecast"><div className="panel-heading"><div><h2><CalendarRange size={19}/> Projeção de pessoal mês a mês</h2><p>Salários, benefícios, encargos e provisões com os reajustes previstos.</p></div><span className="pill">Base cadastrada</span></div><div className="forecast-insights"><article><Users size={19}/><span>Custo médio por pessoa<strong>{money(employees.length?annual/12/employees.length:0)}</strong></span></article><article><TrendingUp size={19}/><span>Impacto anual dos reajustes<strong>{money(impact)}</strong><small>{adjusted.length} pessoas com reajuste previsto</small></span></article><article><CalendarRange size={19}/><span>Mês de maior previsão<strong>{annual?FULL_MONTHS[peak]:'Sem previsão'}</strong><small>{money(totals[peak])}</small></span></article></div><MonthlyChart values={totals} label="Custos de pessoal por mês"/><div className="quarter-summary">{[0,1,2,3].map(q=><div key={q}><span>{q+1}º trimestre</span><strong>{money(totals.slice(q*3,q*3+3).reduce((a,b)=>a+b,0))}</strong></div>)}</div></section>;
}
export function TeamSummary({employees,admin}:{employees:Employee[];admin:boolean}){return <div className="team-summary">{[['Pessoas na equipe',String(employees.length)],['Salário / contrato mensal',money(employees.reduce((v,e)=>v+e.salary,0))],['Benefícios mensais',money(employees.reduce((v,e)=>v+e.meal+e.transport+(e.insuranceMonthly||0),0))],[admin?'Custo anual projetado':'Reajustes previstos',admin?money(employees.reduce((v,e)=>v+costs(e).annual,0)):String(employees.filter(e=>!!e.adjustmentRate).length)]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>;}
export function EmployeeDetails({employee:e,onClose,onEdit}:{employee:Employee;onClose:()=>void;onEdit:()=>void}){const c=costs(e);return <Dialog title={e.name} onClose={onClose} wide><div className="employee-detail-meta"><span>{e.position}</span><span>{e.company||'—'} · {e.sector}</span><span className={'contract '+e.contract}>{e.contract}</span></div><div className="detail-totals"><div><span>Salário / contrato atual</span><strong>{money(e.salary)}</strong></div><div><span>Custo mensal médio</span><strong>{money(c.monthly)}</strong></div><div><span>Custo anual projetado</span><strong>{money(c.annual)}</strong></div></div><h3>Composição anual</h3><div className="cost-breakdown">{[['Salários / contrato',c.salaryAnnual],['VR / VA',e.meal*12],['Vale-transporte',e.transport*12],['Seguro de vida',(e.insuranceMonthly||0)*12],['Bonificação e outros benefícios',c.extras],['INSS orçado',c.inss*12],['FGTS orçado',c.fgts*12],['Provisão de férias',c.vacation],['Provisão de 13º',c.thirteenth]].map(([name,value])=><div key={name}><span>{name}</span><strong>{money(value as number)}</strong></div>)}</div>{!!e.adjustmentRate&&<div className="adjustment-preview"><strong>Reajuste de {(e.adjustmentRate/100).toLocaleString('pt-BR')}% em {FULL_MONTHS[(e.adjustmentMonth||1)-1]}</strong><span>Novo salário / contrato: {money(c.adjustedSalary)} · Impacto anual no custo: {money(c.adjustmentImpact)}</span></div>}<h3>Previsão mensal</h3><MonthlyChart values={c.monthlyValues} label={'Previsão mensal de '+e.name}/>{e.admission&&<p>Admissão: {e.admission.split('-').reverse().join('/')}</p>}{e.notes&&<div className="detail-notes"><h3>Observações</h3><p>{e.notes}</p></div>}<div className="modal-actions"><button className="secondary" onClick={onClose}>Fechar</button><button className="primary" onClick={onEdit}><Pencil size={16}/> Editar cadastro</button></div></Dialog>;}
