'use client';
import {useState} from 'react';
import {Plus,Building2,ShieldCheck,Pencil,Trash2,Save,X} from 'lucide-react';
import {BUDGET_STAGES} from './budget-catalog';
import {groupKey} from './budget-groups';
import BudgetAssignments from './budget-assignments';
export default function SectorBudgets({areas,busy,onSave,error}:{areas:{name:string;budget_groups?:string[]}[];busy:boolean;error?:string;onSave:(b:any)=>Promise<boolean>}){
 const [assigning,setAssigning]=useState<(typeof areas)[number]|null>(null);const [name,setName]=useState(''),[editing,setEditing]=useState<string|null>(null),[newName,setNewName]=useState('');
 return <section className="panel access sector-budgets"><div className="panel-heading"><div><h2>Setores da empresa</h2><p>Organize as equipes e vincule cada gestor à sua área.</p></div><Building2 size={22}/></div><div className="budget-assignments"><ShieldCheck size={18}/><span>A Controladoria define os itens que cada setor deve orçar. Gestores preenchem apenas as despesas atribuídas à própria área.</span></div><form className="sector-create-simple" onSubmit={async e=>{e.preventDefault();if(await onSave({action:'createArea',name,groups:[]}))setName('');}}><label>Nome do setor<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Suprimentos"/></label><button className="primary" disabled={busy||!name.trim()}><Plus size={16}/> Criar setor</button></form><p className="sector-management-note">Ao editar o nome, os funcionários, gestores e orçamentos acompanham a alteração. Só é possível excluir setores sem vínculos.</p><div className="sector-directory">{areas.map(a=><article key={a.name}>{editing===a.name?<form className="sector-rename" onSubmit={async e=>{e.preventDefault();if(await onSave({action:'renameArea',name:a.name,newName}))setEditing(null);}}><label>Novo nome do setor<input autoFocus required maxLength={120} disabled={busy} value={newName} onChange={e=>setNewName(e.target.value)}/></label><div><button type="button" className="secondary" disabled={busy} onClick={()=>setEditing(null)}><X size={14}/> Cancelar</button><button className="primary" disabled={busy||!newName.trim()}><Save size={14}/> Salvar</button></div></form>:<><Building2 size={18}/><div className="sector-card-info"><strong>{a.name}</strong><small>{BUDGET_STAGES.filter(s=>(a.budget_groups||[]).includes(groupKey(s))||(a.budget_groups||[]).includes(`stage:${s.id}`)).length} itens atribuídos</small></div><button className="secondary assign-budget-button" disabled={busy} onClick={()=>setAssigning(a)}>Atribuir orçamento</button><div className="sector-card-actions"><button className="secondary" disabled={busy} aria-label={`Editar setor ${a.name}`} onClick={()=>{setEditing(a.name);setNewName(a.name);}}><Pencil size={14}/> Editar</button><button className="secondary sector-delete" disabled={busy} aria-label={`Excluir setor ${a.name}`} onClick={async()=>{if(confirm(`Excluir o setor ${a.name}? A exclusão só será realizada se ele não tiver funcionários, logins ou orçamentos vinculados.`))await onSave({action:'deleteArea',name:a.name});}}><Trash2 size={14}/> Excluir</button></div></>}</article>)}</div>{assigning&&<BudgetAssignments area={assigning} saveError={error} busy={busy} onSave={onSave} onClose={()=>setAssigning(null)}/>}</section>;
}
