'use client';
import {useState} from 'react';
import {Plus,Save,ChevronDown,ShieldCheck} from 'lucide-react';
import {BUDGET_GROUPS} from './budget-groups';
const categories=[...new Set(BUDGET_GROUPS.map(g=>g.category))];
type Area={name:string;budget_groups?:string[]};
function BudgetChoices({value,onChange,disabled}:{value:string[];onChange:(v:string[])=>void;disabled:boolean}){return <div className="sector-budget-choices">{categories.map(c=>{const groups=BUDGET_GROUPS.filter(g=>g.category===c),count=groups.filter(g=>value.includes(g.id)).length;return <details key={c}><summary>{c}<span>{count}/{groups.length} liberados <ChevronDown size={14}/></span></summary><div>{groups.map(g=><label className="check" key={g.id}><input type="checkbox" disabled={disabled} checked={value.includes(g.id)} onChange={e=>onChange(e.target.checked?[...value,g.id]:value.filter(x=>x!==g.id))}/><span>{g.name}</span></label>)}</div></details>;})}</div>}
function AreaBudgetForm({area,busy,onSave}:{area:Area;busy:boolean;onSave:(b:any)=>Promise<boolean>}){const [groups,setGroups]=useState(area.budget_groups||[]),[open,setOpen]=useState(false);const changed=JSON.stringify([...groups].sort())!==JSON.stringify([...(area.budget_groups||[])].sort());return <article className="sector-permission"><button type="button" className="sector-permission-heading" onClick={()=>setOpen(!open)} aria-expanded={open}><div><strong>{area.name}</strong><small>{(area.budget_groups||[]).length?`${area.budget_groups!.length} orçamentos liberados`:'Nenhum orçamento liberado — configure o acesso'}</small></div><span>Definir orçamentos <ChevronDown size={15}/></span></button>{open&&<div className="sector-permission-body"><p>Marque somente os orçamentos que os gestores de <strong>{area.name}</strong> devem preencher. Os demais ficam ocultos e bloqueados.</p><BudgetChoices value={groups} onChange={setGroups} disabled={busy}/><div className="sector-permission-save"><span>{groups.length} selecionados{changed?' • alterações não salvas':''}</span><button className="primary" disabled={busy||!changed} onClick={()=>onSave({action:'saveAreaBudgets',name:area.name,groups})}><Save size={15}/> Salvar permissões</button></div></div>}</article>}
export default function SectorBudgets({areas,busy,onSave}:{areas:Area[];busy:boolean;onSave:(b:any)=>Promise<boolean>}){const [name,setName]=useState(''),[groups,setGroups]=useState<string[]>([]);return <section className="panel access sector-budgets"><div className="panel-heading"><div><h2>Setores e orçamentos</h2><p>Defina o que cada área pode preencher.</p></div><ShieldCheck size={22}/></div><form className="sector-create" onSubmit={async e=>{e.preventDefault();if(await onSave({action:'createArea',name,groups})){setName('');setGroups([]);}}}><label>Nome do setor<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Suprimentos"/></label><div className="sector-create-heading"><strong>Quais orçamentos este setor deve preencher?</strong><p>Abra uma categoria e marque os orçamentos. Ex.: somente Material de Escritório / Consumo.</p></div><BudgetChoices value={groups} onChange={setGroups} disabled={busy}/><div className="sector-permission-save"><span>{groups.length?`${groups.length} orçamentos selecionados`:'Selecione ao menos um orçamento'}</span><button className="primary" disabled={busy||!groups.length}><Plus size={16}/> Criar setor</button></div></form><div className="sector-existing-heading"><h3>Setores já cadastrados</h3><p>As permissões se aplicam a todos os gestores vinculados ao setor.</p></div>{areas.map(a=><AreaBudgetForm key={a.name+JSON.stringify(a.budget_groups)} area={a} busy={busy} onSave={onSave}/>)}</section>}
