import {withPayroll,payrollEmployee} from '../../payroll-budget';
import {COMPANIES} from '../../payroll-rules';
import { db,getMember } from '../../auth';
import {personnelSheet,type RecordRow} from '../../report';
import {budgetSheet} from '../../budget-report';
import {excelFile} from '../../excel';
import type {BudgetPlan} from '../../budget-types';
export const dynamic='force-dynamic';
export async function GET(req?:Request){try{const m=await getMember(req);if(!m)return Response.json({error:'Faça login para continuar.'},{status:401});if(m.role!=='admin')return Response.json({error:'Exportação restrita ao administrador.'},{status:403});const params=req?new URL(req.url).searchParams:new URLSearchParams(),company=params.get('company'),sector=params.get('sector');if(company&&!(COMPANIES as readonly string[]).includes(company))return Response.json({error:'Empresa inválida.'},{status:400});if(sector&&sector.length>120)return Response.json({error:'Setor inválido.'},{status:400});const year=Number(params.get('year')||2027);if(!Number.isInteger(year)||year<2020||year>2100)return Response.json({error:'Ano inválido.'},{status:400});const where:string[]=[],values:string[]=[];if(company){where.push('company=?');values.push(company);}if(sector){where.push('sector=?');values.push(sector);}const records=(await db().prepare('SELECT * FROM employees'+(where.length?' WHERE '+where.join(' AND '):'')+' ORDER BY sector,name').bind(...values).all()).results.map((r:any)=>({...r,adjustmentRate:r.adjustment_rate,adjustmentMonth:r.adjustment_month,inssRate:r.inss_rate,fgtsRate:r.fgts_rate,vacationFactor:r.vacation_factor,thirteenthFactor:r.thirteenth_factor,bonusAnnual:r.bonus_annual,insuranceMonthly:r.insurance_monthly,otherAnnual:r.other_annual})) as unknown as RecordRow[];const areas=(await db().prepare('SELECT name FROM areas ORDER BY name').all()).results.map((a:any)=>a.name);const budgetWhere=['year=?',...where],budgetValues=[year,...values];const plans=(await db().prepare('SELECT * FROM budget_plans WHERE '+budgetWhere.join(' AND ')+' ORDER BY company,sector').bind(...budgetValues).all()).results as unknown as BudgetPlan[];const bytes=excelFile([budgetSheet(withPayroll(plans,records.map(payrollEmployee),year),year),personnelSheet(records,areas,year)]);return new Response(bytes as unknown as BodyInit,{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="REM_Controladoria_${year}_${new Date().toISOString().slice(0,10)}.xlsx"`,'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:'Não foi possível gerar o relatório. Tente novamente.'},{status:503});}}
