import {enrichPayroll} from '../../../payroll-budget-server';
import {PAYROLL_STAGE_IDS} from '../../../payroll-budget';
import {allowedBudgetStages,limitAmounts} from '../../../budget-access';
import {BUDGET_STAGES} from '../../../budget-catalog';
import {db,getMember} from '../../../auth';
import {makeBudgetReport} from '../../../budget-report';
import type {BudgetPlan} from '../../../budget-types';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{const m=await getMember(req);if(!m)return Response.json({error:'Faça login para continuar.'},{status:401});if(m.role!=='admin')return Response.json({error:'O orçamento é exclusivo da Controladoria.'},{status:403});const u=new URL(req.url),year=Number(u.searchParams.get('year')||2027);if(!Number.isInteger(year)||year<2020||year>2100)return Response.json({error:'Ano inválido.'},{status:400});if(m.role!=='admin'&&u.searchParams.get('sector')&&u.searchParams.get('sector')!==m.sector)return Response.json({error:'Este orçamento pertence a outro setor.'},{status:403});let plans=(await(m.role==='admin'?db().prepare('SELECT * FROM budget_plans WHERE year=? ORDER BY company,sector').bind(year):db().prepare('SELECT * FROM budget_plans WHERE year=? AND sector=? ORDER BY company').bind(year,m.sector)).all()).results as unknown as BudgetPlan[];const company=u.searchParams.get('company'),sector=u.searchParams.get('sector');plans=await enrichPayroll(plans,year,m.role==='admin'?sector||undefined:m.sector,company||undefined);if(company)plans=plans.filter(p=>p.company===company);if(sector)plans=plans.filter(p=>p.sector===sector);let stages=m.role==='admin'?BUDGET_STAGES:await allowedBudgetStages(m.sector);if(plans.some(p=>PAYROLL_STAGE_IDS.some(id=>p.amounts[id]?.some(v=>v>0))))stages=BUDGET_STAGES.filter(s=>stages.some(t=>t.id===s.id)||PAYROLL_STAGE_IDS.includes(s.id));if(!stages.length)return Response.json({error:'Nenhum orçamento foi liberado para seu setor.'},{status:403});if(m.role!=='admin'){const ids=new Set<string>(stages.map(s=>s.id));plans=plans.map(p=>({...p,amounts:limitAmounts(p.amounts,ids)}));}if(!plans.length)return Response.json({error:'Salve um orçamento antes de exportar.'},{status:400});return new Response(makeBudgetReport(plans,year,stages) as unknown as BodyInit,{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="REM_Orcamento_${year}.xlsx"`,'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:'Não foi possível exportar o orçamento.'},{status:503});}}
